baseurl = "https://nalbertg.github.io/"
languageCode = "en-us"
title = "Nalbert Leal"
theme = "hugo-strata-theme"
disqusShortname = "spf13"
# Enable Google Analytics by inserting your tracking code
googleAnalytics = ""
# Define how many posts should appear on a site
paginate = 10

[params]
	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Nalbert Leal"
	description = "My personal blog. What i am thinking, learning, testing and developing are the focus here."

	# Format dates with Go's time formatting
	date_format = "01-02-2006"

	# Add read time estimates in the format "X min read"
	show_read_time = true

	# Add custom assets with their paths relative to the static folder
	custom_js   = []
	custom_css  = []


	[params.sidebar]
		# Replace the avatar with a picture of your own under static/images
		avatar = "nalbertLeal.jpg"
		# Use Markdown to format the string. This works nearly all over the theme
		bio = "**I'm Nalbert**, that's my personal blog.<br> What i am thinking, learning, testing<br> and developing are the focus here."
		# The icons will be shown if you enter your username
		twitter = ""
		github = "nalbertg"
		gitlab = ""
		dribbble = ""
		facebook = ""
		googleplus = ""
		flickr = ""
		linkedin = ""

		copyright = [
			"&copy; Nalbert Leal",
			"Design: [HTML5 UP](//html5up.net)"
		]


	[params.about]
		hide  = false
		title = "Bio."
		content = "Hi, my name is Nalbert Gabriel Melo Leal. I'm 20 years old, live in Brazil and study software engineering at Federal Univesity of Rio Grande do Norte. I started to program when I was just 10 years old with javascript and since there I have every day tried to be a bether developer. Today i like to code backend with python, javascript and golang but usualy I try to learn some new and weird language."


	[params.portfolio]
		hide  = false
		title = "Recent Work - Imagens"

		# The images and thumbnails are stored under static/images
		# Create and change subfolders as you like
		[[params.portfolio.gallery]]
			image = "portfolio/18580813_747356378722668_8714861240586862592_n.jpg"
			thumb = "portfolio/18580813_747356378722668_8714861240586862592_n.jpg"
			title = "Coffe + long nigth"
			description = "A big cup of coffe to don't sleep before finish the work."

	[params.recentposts]
		hide  = false
		title = "Recent blog posts"

	[params.contact]
		hide  = false
		title = "Get In Touch"
		content = "For this first moment the contact form below doesn't work. So if you want to contact me, send the mesage to the email on the left side the form, it's the best option."

		# This can be exact coordinates or a searchable address in google maps
		gmaps_address = "-5.8830000, -35.2090000"
		address = [
			"Padre Rodolfo Lukebin, 36",
			"Parnamirim, Nova Parnamirim",
			"Brazil"
		]
		phone = "+55 (84) 998326817"

		# Since this template is static, the contact form uses www.formspree.io as a
		# proxy. The form makes a POST request to their servers to send the actual
		# email. Visitors can send up to a 1000 emails each month for free.
	    #
	    # What you need to do for the setup?
	    #
	    # - set your email address under 'email' below
	    # - upload the generated site to your server
	    # - send a dummy email yourself to confirm your account
	    # - click the confirm link in the email from www.formspree.io
	    # - you're done. Happy mailing!
		email = "nalbertg@outlook.com"

		[params.contact.form]
			# Set custom strings for the form if your native
			# language isn't English
			name = "Name"
			email = "Email"
			message = "Message"
			submit = "Send message"


# Menu links that appear on the left sidebar
[[menu.main]]
	name = "Home"
	url  = "/"
	weight = 10

[[menu.main]]
	name = "Blog"
	url  = "post/"
	weight = 0
